### PR TITLE
[Update] Kernel 3.19.2

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Hi - unfortunately I can't merge this for a couple of reasons.
One - we now do it on the mailing list as mentioned in README.md, and secondly
this update would cause a boot failure :)

The initrd needs to be changed in the post install (see the comar file), the actions.py needs updating to reflect the new version, plus *ideally* the new config should be refreshed. (Currently it would depmod and create a dracut for 3.19.1. leaving you with no initrd on boot)

With that said, I'll get this one quickly updated myself. Thanks for informing me though! :)

**Comment by ovr** [comment]
@ikeydoherty 
Thank you for answer

At all I am interested to help project

For example contribute repository
Can you create a simple instructions for test software?

Next
I am interested to contibute website code
Can you push it on github?

Next
I am interested to create software panel for pisi repository
I mean web site on php that index pisi packages, show updates and allows to search any packages

**Comment by Justinzobel** [comment]
@ovr 
Packaging Guide is here: https://evolve-os.com/forums/viewtopic.php?f=17&t=82 as far as testing, test it works on your machine, then send it in.

As for listing the packages that can be done in the OS with eopkg list-available or searching in the Software Center

**Comment by ovr** [comment]
@Justinzobel 
Awesome! Thanks you, i will research this way...

But it's realy hard I think We need to implement more better way with CI testing

**Comment by ovr** [comment]
@ikeydoherty 
At this repo is a fork
YOu need to repush it without fork flag

+ Issues is not opened for fork now
+ Github show stp messages for example
(This branch is 1079 commits ahead of SolusOS-discontinued:master)

Thank for awesome OS ;)

**Comment by ikeydoherty** [comment]
I know its a fork.. I forked it. I made SolusOS too :p

**Pull request closed without merging**
