### PR TITLE
[NEW] atom

### PR DESCRIPTION
**Pull request by poltertec**
This should be better :blush: :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by poltertec** [comment]
libdrm update resolved my graph probs at boot (no signal to monitor - already improved after latest kernel fixes)
rebooted 10 times in row out of pure joy :)

**Comment by Justinzobel** [comment]
@poltertec Items in the repository must be from source not deb, build instructions are here https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md and all changes to the repository must be done via git send-email to:packaging@evolve-os.com

**Comment by Justinzobel** [comment]
nodejs has been updated already and I've submitted an update to libdrm

**Comment by poltertec** [comment]
Hey justin aware of the new method (old request).
Think i used the deb because i was having trouble with grunt in evobuild
will close this request

**Pull request closed without merging**
